from prometheus_client import Counter, Gauge, Histogram

REQUESTS = Counter("smart_router_requests_total", "Requests", ["endpoint", "mode", "kind", "stream", "status"])
DURATION = Histogram("smart_router_request_duration_seconds", "Request duration", ["mode", "kind", "stream"])
PROPOSED_TIERS = Counter("smart_router_proposed_tiers_total", "Proposed tiers", ["mode", "tier", "reason"])
PROPOSED_OUTPUT = Histogram("smart_router_proposed_output_tokens", "Proposed output token budgets")
EFFECTIVE_OUTPUT = Histogram("smart_router_effective_output_tokens", "Effective output token budgets")
BUDGET_ENFORCEMENTS = Counter("smart_router_budget_enforcements_total", "Budget enforcement", ["tier", "field"])
TOKEN_ESTIMATES = Counter("smart_router_token_estimates_total", "Estimated tokens", ["kind"])
STICKY = Counter("smart_router_sticky_total", "Sticky session actions", ["action", "source", "tier"])
FAIL_OPEN = Counter("smart_router_fail_open_total", "Fail-open events", ["reason"])
UPSTREAM_ERRORS = Counter("smart_router_upstream_errors_total", "Upstream errors", ["status"])
UPSTREAM_INPUT_TOKENS = Counter("smart_router_upstream_input_tokens_total", "Upstream input tokens")
UPSTREAM_CACHED_INPUT_TOKENS = Counter("smart_router_upstream_cached_input_tokens_total", "Cached input tokens")
UPSTREAM_OUTPUT_TOKENS = Counter("smart_router_upstream_output_tokens_total", "Upstream output tokens")
USAGE_MISSING = Counter("smart_router_usage_missing_total", "Responses without usage", ["stream"])
ACTIVE_STREAMS = Gauge("smart_router_active_streams", "Active streaming requests")
READINESS = Gauge("smart_router_readiness", "Readiness components", ["component"])
LEARNED_INFERENCE_SECONDS = Histogram("smart_router_learned_inference_seconds", "Learned policy inference time")
LEARNED_FALLBACKS = Counter("smart_router_learned_fallbacks_total", "Learned policy fallbacks", ["reason"])
