"""Approval-gated package installation policy for Hermes.

Only exact PyPI/npm versions are accepted. Install commands are generated by the
plugin, never model-controlled, and each prepared operation has a one-time rule.
"""
from __future__ import annotations

import json
import os
import re
import secrets
import subprocess
import sys
from pathlib import Path
from typing import Any

_PYTHON_TARGET = Path(os.getenv("HERMES_LAZY_INSTALL_TARGET", "/opt/data/lazy-packages"))
_NPM_PREFIX = Path(os.getenv("NPM_CONFIG_PREFIX", "/opt/data/npm-packages"))
_NPM_REGISTRY = os.getenv("STACK_NPM_REGISTRY", "https://registry.npmjs.org/")
_PLUGIN_DIR = Path(__file__).resolve().parent
_NPM_USER_CONFIG = _PLUGIN_DIR / "npm-user.npmrc"
_NPM_GLOBAL_CONFIG = _PLUGIN_DIR / "npm-global.npmrc"
_runtime_context: Any = None
_operations: dict[str, dict[str, Any]] = {}

_PY_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]{0,127})==([0-9]+(?:\.[0-9A-Za-z-]+)+)$")
_NPM_RE = re.compile(r"^((?:@[a-z0-9][a-z0-9._-]*/)?[a-z0-9][a-z0-9._-]*)@([0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?)$")
_RAW_MANAGER_RE = re.compile(r"(?:^|[;&|()\s])(?:sudo\s+)?(?:python(?:3)?\s+-m\s+pip|pip(?:3)?|uv\s+pip|npm|npx|yarn|pnpm|corepack|apt(?:-get)?|hermes\s+skills\s+install)\b", re.I)
_STRIPPED_ENV = frozenset({"NODE_OPTIONS", "NODE_PATH", "PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP"})


def _json(v: Any) -> str: return json.dumps(v, separators=(",", ":"), sort_keys=True)
def _error(m: str) -> str: return _json({"error": m})

def _ctx_value(*names: str, default: Any = None) -> Any:
    if _runtime_context is None: return default
    for name in names:
        value = getattr(_runtime_context, name, None)
        if callable(value):
            try: return value()
            except TypeError: continue
        if value is not None: return value
    return default

def _current_session_key() -> str: return str(_ctx_value("current_session_key", "session_key", default=os.getenv("HERMES_SESSION_KEY", "")) or "")
def _session_platform() -> str:
    value = _ctx_value("session_platform", "platform")
    if value: return str(value)
    key = _current_session_key(); return key.split(":", 1)[0] if ":" in key else ""
def _cron_context() -> bool: return bool(_ctx_value("cron_context", "is_cron", default=False))
def _approval_bypass_active() -> bool: return bool(_ctx_value("approval_bypass_active", "approval_bypass", default=False))
def _manual_approval_mode() -> bool: return bool(_ctx_value("manual_approval_mode", "is_manual_approval", default=False))

def _context_problem() -> str | None:
    if _session_platform() != "telegram" or not _current_session_key(): return "Package installation is allowed only from an interactive Telegram session."
    if _cron_context() or _approval_bypass_active() or not _manual_approval_mode(): return "Package installation requires the normal interactive manual-approval path."
    return None

def _prepare(kind: str, spec: str) -> str:
    if problem := _context_problem(): return _error(problem)
    match = (_PY_RE if kind == "python" else _NPM_RE).fullmatch(spec.strip() if isinstance(spec, str) else "")
    if not match: return _error(f"{kind} package must use an exact trusted registry version.")
    package, version = match.groups()
    pending_id = secrets.token_urlsafe(24)
    if kind == "python":
        destination = str(_PYTHON_TARGET)
        command = [sys.executable, "-m", "pip", "install", "--disable-pip-version-check", "--no-input", "--only-binary=:all:", "--target", destination, f"{package}=={version}"]
    else:
        destination = str(_NPM_PREFIX)
        command = ["npm", "install", "--global", "--prefix", destination, "--registry", _NPM_REGISTRY, "--ignore-scripts", "--no-audit", "--no-fund", f"{package}@{version}"]
    _operations[pending_id] = {"kind": kind, "package": package, "version": version, "destination": destination, "command": command, "session": _current_session_key(), "state": "prepared"}
    return _json({"status": "prepared", "pending_id": pending_id, "package": package, "version": version, "destination": destination, "command": command})

def _prepare_python(payload: dict[str, Any]) -> str: return _prepare("python", payload.get("spec", ""))
def _prepare_npm(payload: dict[str, Any]) -> str: return _prepare("npm", payload.get("spec", ""))

def _clean_env(kind: str) -> dict[str, str]:
    env = os.environ.copy()
    for key in list(env):
        upper = key.upper()
        if upper.startswith("NPM_CONFIG_") or upper in _STRIPPED_ENV or upper in {"PIP_INDEX_URL", "PIP_EXTRA_INDEX_URL", "UV_INDEX_URL", "UV_EXTRA_INDEX_URL"}:
            env.pop(key, None)
    env["PIP_CONFIG_FILE"] = os.devnull
    if kind == "npm":
        env.update({
            "NPM_CONFIG_USERCONFIG": str(_NPM_USER_CONFIG),
            "NPM_CONFIG_GLOBALCONFIG": str(_NPM_GLOBAL_CONFIG),
            "NPM_CONFIG_IGNORE_SCRIPTS": "true",
            "NPM_CONFIG_AUDIT": "false",
            "NPM_CONFIG_FUND": "false",
        })
    return env

def _install(kind: str, payload: dict[str, Any]) -> str:
    pending_id = str(payload.get("pending_id", "")); item = _operations.get(pending_id)
    if not item or item.get("kind") != kind or item.get("state") != "approved_once": return _error("Unknown, expired, or unapproved package operation.")
    if item["session"] != _current_session_key(): item["state"] = "cancelled"; return _error("The approved package operation belongs to another session.")
    if problem := _context_problem(): item["state"] = "cancelled"; return _error(problem)
    # Consume before invoking a package manager so replay is impossible even on failure.
    item["state"] = "consumed"; _operations.pop(pending_id, None)
    destination = Path(item["destination"]); destination.mkdir(parents=True, exist_ok=True)
    try:
        completed = subprocess.run(item["command"], shell=False, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=300, env=_clean_env(kind), check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        return _error(f"Package installer failed to start: {type(exc).__name__}.")
    result = {"status": "installed" if completed.returncode == 0 else "failed", "returncode": completed.returncode, "output": (completed.stdout + completed.stderr)[-8000:]}
    return _json(result)

def _install_python(payload: dict[str, Any]) -> str: return _install("python", payload)
def _install_npm(payload: dict[str, Any]) -> str: return _install("npm", payload)

def _pre_tool_call(tool_name: str, arguments: dict[str, Any] | None = None):
    arguments = arguments or {}
    if tool_name == "terminal" and _RAW_MANAGER_RE.search(str(arguments.get("command", ""))):
        return {"action": "block", "reason": "Raw package-manager commands are blocked; use the approval-gated package tools."}
    if tool_name in {"write_file", "edit_file", "patch_file"}:
        try: path = Path(str(arguments.get("path", ""))).resolve()
        except (OSError, ValueError): path = Path("/")
        for managed in (_PYTHON_TARGET, _NPM_PREFIX):
            try:
                if path == managed.resolve() or managed.resolve() in path.parents:
                    return {"action": "block", "reason": "Direct writes to managed package targets are blocked."}
            except OSError: pass
    expected = {"stack_install_python_package": "python", "stack_install_npm_package": "npm"}.get(tool_name)
    if not expected: return None
    pending_id = str(arguments.get("pending_id", "")); item = _operations.get(pending_id)
    if not item or item.get("kind") != expected or item.get("state") != "prepared" or item.get("session") != _current_session_key():
        return {"action": "block", "reason": "Install requires a matching prepared one-time operation."}
    item["state"] = "approved_once"; item["rule_key"] = f"stack-package-install:{pending_id}"
    return {"action": "approve", "rule_key": item["rule_key"], "description": f"Install exact {item['package']} {item['version']} once."}

def _post_approval_response(pattern_key: str, choice: str, **_: Any):
    key = str(pattern_key).removeprefix("plugin_rule:")
    for pending_id, item in list(_operations.items()):
        if item.get("rule_key") != key or item.get("state") not in {"approved_once", "approval_pending"}: continue
        if choice == "once": item["state"] = "approved_once"
        else: item["state"] = "cancelled"
        return

def _tool(name: str, description: str, handler, properties: dict[str, Any], required: list[str]):
    return dict(name=name, description=description, handler=handler, schema={"parameters": {"type": "object", "properties": properties, "required": required, "additionalProperties": False}})

def register(context):
    global _runtime_context
    _runtime_context = context
    for definition in [
        _tool("stack_prepare_python_package", "Prepare an exact PyPI package version for one-time approval.", _prepare_python, {"spec": {"type": "string"}}, ["spec"]),
        _tool("stack_install_python_package", "Install a previously prepared and approved Python package.", _install_python, {"pending_id": {"type": "string"}}, ["pending_id"]),
        _tool("stack_prepare_npm_package", "Prepare an exact npm package version for one-time approval.", _prepare_npm, {"spec": {"type": "string"}}, ["spec"]),
        _tool("stack_install_npm_package", "Install a previously prepared and approved npm package.", _install_npm, {"pending_id": {"type": "string"}}, ["pending_id"]),
    ]:
        context.register_tool(**definition)
    context.register_hook("pre_tool_call", _pre_tool_call)
    context.register_hook("post_approval_response", _post_approval_response)
